### ISSUE TITLE
rebind?

### ISSUE THREAD

**Issue by Fan4eGGG** [Ryuu43/CS2-AHK-Bhop#2]
sup!
wanna use ur ahk, but my jump button is **mouse5** for 15 years already.
how can i change the script to hold **mouse5** and jump?
thank you.

**Comment by Ryuu43** [comment]
You can go into the script and change the line Xbutton1 to Xbutton2
![image](https://github.com/Ryuu43/CS2-AHK-Bhop/assets/72246166/d14a5cff-7492-482d-b43c-0ab4a328499e)

**Comment by Fan4eGGG** [comment]
Yeah, so you can't change "_WheelDown_" in any way? For example, I have **smoke** on WheelDown and **flash** on WheelUp and now it's not very convenient :D 
I understand it's a feature of this ahk?

**Comment by Fan4eGGG** [comment]
> I don't think I have those features set up

u mean it can't be changed? I mean WheelDown will still be on the jump no matter what? dont get it :(

**Comment by Fan4eGGG** [comment]
sooo 👉🏻👈🏻

**Comment by Ryuu43** [comment]
> sooo 👉🏻👈🏻

The code is simulate mouse wheel down on jump soo yeh but if u want i can change it

**Comment by Ryuu43** [comment]
so I have updated the new one, you can check it out

**Comment by Fan4eGGG** [comment]
oh, thanks for that! take my star.
i just don't know much about this whole "coding" thing. i have another question about the "**contrstrafing**" thing.
when i jump, i just lose speed, do i need to do anything else?
thanks.

**Comment by Ryuu43** [comment]
I tried many edits but none worked. CS2 auto bhop will and never will be like CSGO if Valve doesn't fix the subtick input that makes each jump become inaccurate and random. So far I have tested but none of the AHK bhops work

**Comment by Fan4eGGG** [comment]
get it.
I was just watching your video and your speed doesnt drop, its up. when I jump, my speed just goes down :D

**Comment by Ryuu43** [comment]
In that video I used the mouse wheel bind. According to my testing with mouse scrolling and spaces, mouse scrolling always gives height 54.66 and the space bind give random height from 54.65 to 54.68. So each jump with the mouse wheel is always consistent. Unlike Space bind, you will lose speed

**Comment by Fan4eGGG** [comment]
oh, now i see.
thanks for clearing that up.
